baseURL: http://www.example.com
title: HOME
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Paniti Thongmon
  avatarURL: images/profile3.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: John Doe's personal website
  hideColorSchemeToggle: no
  info:
    - Mathematics teacher
  keywords: blog,developer,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2019
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/pth64/
      weight: 1
    - icon: fa fa-2x fa-instagram
      name: instagram
      url: https://www.instagram.com/panitii
      weight: 1
    - icon: fa fa-2x fa-facebook
      name: facebook
      url: https://www.facebook.com/iomex
      weight: 2
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: Profile
          url: about/
          weight: 1
        - name: Projects
          url: posts/
          weight: 2
        - name: Contact me
          url: contact/
          weight: 5